# Generated by Django 4.1 on 2022-08-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accumulated_points',
            field=models.IntegerField(default=0),
        ),
    ]
